### ISSUE TITLE
[Request] Additional tag or different icon for rss/feed folders

### ISSUE THREAD

**Issue by Aris-t2** [nt1m/livemarks#60]
At the moment there is no visual difference between default bookmark folder icons and a rss/feed folder icons.

Please add a different icon to feed folders or at least an exclusive tag, so the folder can be determined by CSS and manually styled in userChrome.css.

**Comment by nt1m** [comment]
Bookmark tags are currently not changeable via the WE API. There's currently a bug filed about it: https://bugzilla.mozilla.org/show_bug.cgi?id=1225916

Icons can't be changed either.

I guess the best I can do here is add support for some kind of title prefix for the bookmark folder ?

**Comment by Aris-t2** [comment]
Thanks for the answer.

So for now we only can achieve something like this with custom code based on folder label in userChrome.css:

```css
.bookmark-item[label="label_of_feed_folder"] .toolbarbutton-icon {
  list-style-image: url("path_to_icon") !important;
}
```

**Comment by GrosBourrin** [comment]
in userChrome.css 👍 

#bookmarks-view treechildren::-moz-tree-image(container), #PlacesToolbarItems toolbarbutton[container="true"], #PlacesToolbarItems menu[container="true"] .menu-iconic-left, #BMB_bookmarksPopup menu[container="true"] .menu-iconic-icon, #bookmarksMenu menu[container="true"] .menu-iconic-icon, .bookmark-item[container] { list-style-image: url("folder5.svg") !important; /* place svg file in the same folder of the css */ }

replace folder5.svg by this:  

![rss2](https://user-images.githubusercontent.com/40931468/50379607-3e109280-064e-11e9-89ec-ea0f77e3ede0.png) https://github.com/GrosBourrin/FIREFOX-BLUE-MOON/blob/master/rss%20svg4.svg
![rss1](https://user-images.githubusercontent.com/40931468/50379609-436ddd00-064e-11e9-8266-2a27480cdcb9.png) https://github.com/GrosBourrin/FIREFOX-BLUE-MOON/blob/master/rss3.svg

right click on link then save target link

you can edit svg files with gravit from gravit.io

**Comment by Aris-t2** [comment]
@GrosBourrin 
Doing this will override all bookmark folders, not just those of rss feeds.

Better to insert rss feed folder names manually to not override other folders like shown in this example:

```css
.bookmark-item[container="true"]:-moz-any([label="rssfeed_name1"],[label="rssfeed_name2"],[label="rssfeed_name3"],[label="rssfeed_name4"]) {
  list-style-image: url("./rss.svg") !important;
  -moz-image-region: rect(0, 16px, 16px, 0) !important;
}
```
