### ISSUE TITLE
Is possible to change folder icon?

### ISSUE THREAD

**Issue by gabri25ele** [nt1m/livemarks#83]
Is possible to change the folder icon?
Now is standard folder like a standard folder bookmark.

**Comment by nt1m** [comment]
Unfortunately, the WebExtension API does not let us do this.

**Comment by Madis0** [comment]
For now, you could at least append an emoji to the start of the name, to differentiate them from normal folders. Maybe one of those: 🔶🆚📶🔁↗️🔔

**Comment by GrosBourrin** [comment]
change the icon folders of the bookmarks toolbar !

in the userChrome.css 👍 

#bookmarks-view treechildren::-moz-tree-image(container),
#PlacesToolbarItems toolbarbutton[container="true"],
#PlacesToolbarItems menu[container="true"] .menu-iconic-left,
#BMB_bookmarksPopup menu[container="true"] .menu-iconic-icon,
#bookmarksMenu menu[container="true"] .menu-iconic-icon,
.bookmark-item[container] {
	list-style-image: url("folder5.svg") !important; /* place svg file in the same folder of the css */
}

**Comment by GrosBourrin** [comment]
replace folder5.svg by this 👍 

![rss2](https://user-images.githubusercontent.com/40931468/50379607-3e109280-064e-11e9-89ec-ea0f77e3ede0.png)
![rss1](https://user-images.githubusercontent.com/40931468/50379609-436ddd00-064e-11e9-8266-2a27480cdcb9.png)

**Comment by mpred04** [comment]
> 
> 
> change the icon folders of the bookmarks toolbar !
> 
> in the userChrome.css +1
> `#bookmarks-view treechildren::-moz-tree-image(container), #PlacesToolbarItems toolbarbutton[container="true"], #PlacesToolbarItems menu[container="true"] .menu-iconic-left, #BMB_bookmarksPopup menu[container="true"] .menu-iconic-icon, #bookmarksMenu menu[container="true"] .menu-iconic-icon, .bookmark-item[container] { list-style-image: url("folder5.svg") !important; /* place svg file in the same folder of the css */ }`

Just so it's clear - this changes every folder icon not just for livemarks folders, correct?

**Comment by GrosBourrin** [comment]
well yes, that's impossible to change the icon of the webext folders , you can eventually change the other folders by naming them one by one : 


.bookmark-item[container="true"] [label="Label of the folder"] {
	list-style-image: url("folder_icon.svg") !important;
}

**Comment by mpred04** [comment]
> 
> 
> well yes, that's impossible to change the icon of the webext folders , you can eventually change the other folders by naming them one by one :
> 
> ```
> 
> .bookmark-item[container="true"] [label="Label of the folder"] {
> 	list-style-image: url("folder_icon.svg") !important;
> }
> ```

That actually works for me, thank you!

**Comment by GrosBourrin** [comment]
> 
> 
> > well yes, that's impossible to change the icon of the webext folders , you can eventually change the other folders by naming them one by one :
> > ```
> > 
> > .bookmark-item[container="true"] [label="Label of the folder"] {
> > 	list-style-image: url("folder_icon.svg") !important;
> > }
> > ```
> 
> That actually works for me, thank you!

glad to have help you a bit

**Comment by TroudhuK** [comment]
A way to automatize is using prefixes, instead of listing (unread = 1 space, read = 2 spaces, + 1 space added between prefix and URL):
```CSS
.bookmark-item[container][label^="  "], /* ADDED */
.bookmark-item[container][livemark] {
  list-style-image: url("./../../image/livemark-folder.png") !important;
  -moz-image-region: auto !important;
}
/* ADDED */
.bookmark-item[container][label^="  "] > .toolbarbutton-text {
  margin-left: -6px !important;
}
.bookmark-item[container][label^="   "] > .toolbarbutton-text {
  margin-left: -9px !important;
}
```
(Set image URL and size of spaces, 3px for me)
https://github.com/Aris-t2/CustomCSSforFx/issues/211#issuecomment-520222395
